apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers
rules:
  - apiGroups:
    - ""
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
    - create
    - update            