apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers
subjects:
  - kind: Group
    name: developers
    namespace: app
    apiGroup: rbac.authorization.k8s.io
			
roleRef:
  kind: Role
  name: developers
  apiGroup: rbac.authorization.k8s.io