apiVersion: v1
kind: Service 
metadata:
  name: shifts-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: shifts
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port


