# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users
spec:
  selector:
    app: users
  type:  LoadBalancer
  ports:
  - nodePort: 32553
    port: 8080
    targetPort: 8080